### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-php#2]
# Description

This issue describes the set of tasks to complete in order to finish up work on the library.

# Tasks

- [x] Touch base with the @jobarratt and @pwalsh to notify that you consider the work complete
- [x] Provide a short description / link to code for how each action is implemented, with a link to unit tests that prove each action
- [x] Tag your candidate code as v0.1
- [x] Setup travis to auto deploy tagged versions to the package management solution for your language
- [ ] Ensure that the OKI account on the package management platform is an administrator/maintainer of the package, along with yourself
- [ ] Receive code review from @pwalsh and address any remaining issues
- [ ] Publish final version

**Comment by OriHoch** [comment]
@jobarratt and @pwalsh - touching base and notifying you that I consider the work complete

README contains a summary of available actions and usage.

Unit tests are in tests directory, with self-explanatory names.

final code is release on github (v0.1.4) and published to packagist: https://packagist.org/packages/frictionlessdata/datapackage

travis works but does not publish to packagist yet, will be handled in #26

what's your username in packagist? is it oki?

**Comment by OriHoch** [comment]
packagist is connected directly to github (without travis) - so now every tag automatically updates packagist

**Comment by pwalsh** [comment]
@roll @brew can you check the details of our account on Packagist, or, create one if there is not one.

**Comment by pwalsh** [comment]
@OriHoch thanks so much! will review this week

**Comment by roll** [comment]
Hi @DiegoPino,

What do you think whether it's possible to release tableschema/datapackage v1 for PHP?

https://github.com/frictionlessdata/libraries#current-status

**Comment by DiegoPino** [comment]
Sure. On it. I should add the git tests integration too. I will have this by the end of the week.

**Comment by roll** [comment]
Thanks a lot!
